### ISSUE TITLE
[1.21] Bigger Stack Size Not stacking potions

### ISSUE THREAD

**Issue by ffuentesm** [Jodekq/Color-Properties#1]
Hello, Your modrinth mod page just said to open an issue on github, but there wasn't any page for the Bigger Stack Size mod. So I am posting it here. 
https://modrinth.com/datapack/bigger-stack-size

I am using the Datapack version BiggerStackSize-[1.21]-v.1.1.0 of the mod since I am on NeoForge, and the mod version was only for Forge and fabric. 

So, I already tried everything that the page said, but for some reason, potion bottles of the same type are not stacking.

**Comment by Jodekq** [comment]
Oh yeah, didn't create a page for that yet. There's also a discord server but I'll answer it here.

I'll have a look later and fix the issue, thank you! :)

I'll let you know when I found something

**Comment by Jodekq** [comment]
Found the issue and fixxed it, thank you! :D
